---
title: "Project 3"
author: "Sasank Desaraju, Phuc Pham, Natalie Geigel, Christopher Ludka"
date: "11/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(car)
library(knitr)
library(emmeans)
library(tidymodels)

```

```{r planned-data-carpentry}
dataset <- readRDS("./data/group3_data.rds")

tidy_dataset <- dataset %>%
  rename(ID = record_id,
         Flanker_test = tb_flanker_unadj_ss,
         Pic_Seq_Mem_Test = tb_picseq_unadj_ss,
         Moca_Score = moca_unadj,
         Musical_Practice = champs_q17c,
         Age = gi_age,
         Education_Level = gi_degree,
         Second_Language = gi_2ndlang_yn,
         Track_Activity = pac_track_doing,
         Paying_Attention = pac_pay_attention,
         Concentration = pac_concentrate,
         Indecisiveness = bdi_indecisiveness,
         Remembering = pac_remember,
         R_Parahippo_vol = fs_parahpc_vol_r,
         L_Parahippo_vol = fs_parahpc_vol_l,
         Est_Tot_intra_cranial_vol = fs_etiv
         ) %>%
  mutate(Musical_Practice = as_factor(Musical_Practice),
         Education_Level = as_factor(Education_Level),
         Second_Language = as_factor(Second_Language),
         Track_Activity = as_factor(Track_Activity),
         Paying_Attention = as_factor(Paying_Attention),
         Concentration = as_factor(Concentration),
         Indecisiveness = as_factor(Indecisiveness),
         Remembering = as_factor(Remembering),
         Moca_Score = as.numeric(Moca_Score))

tidy_dataset
```

```{r exploratory-data-carpentry}
exp_dataset <- tidy_dataset %>%
  filter(redcap_event_name == "event_1_arm_1") %>%
  select(-redcap_event_name) 
# Y (MoCA Score) ~ fct1 (pac_pay_attention) + fct2 (pac_remember) + fct3 (bdi_indecisiveness) + fct4(pac_concentrate) 



#Model 2: understanding factors as related to cognitive impairment compared to moca scores

ggplot(exp_dataset, aes(Paying_Attention,Moca_Score,color = Paying_Attention))+
  geom_boxplot()

ggplot(exp_dataset, aes(Remembering,Moca_Score,color = Remembering))+
  geom_boxplot()

ggplot(exp_dataset, aes(Indecisiveness,Moca_Score,color = Indecisiveness))+
  geom_boxplot()

ggplot(exp_dataset, aes(Concentration,Moca_Score,color = Concentration))+
  geom_boxplot()

# If I drop NA's from every column, the result is only 27 observations which is concerning. It gets rid of indecisive scores of 2
MoCA_dropna <- exp_dataset %>%
  select(Paying_Attention,Remembering,Indecisiveness,Concentration,Moca_Score) 
# %>%
#   drop_na(Paying_Attention,Remembering,Indecisiveness,Concentration)
```